[build]
  command   = "npm run build"
  publish   = "."                     # plugin handles routing/publish
  functions = "netlify/functions"     # plugin will write serverless functions here

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
