import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/ThemeProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ensureUserSession } from "@/lib/auto-guest-login";
import { UserProvider } from "@/context/UserProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Sugary web",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await ensureUserSession();
  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning>
        <ThemeProvider>
          <TooltipProvider>
            <UserProvider>{children}</UserProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
