import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/ThemeProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { UserProvider } from "@/context/UserProvider";
import { Toaster } from "sonner";
import Script from "next/script";
import { getCurrentUser } from "@/actions/auth/getCurrentUser";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Sugary web",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const result = await getCurrentUser();
  const initialUser = result.success ? result.user : null;

  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning>
        <ThemeProvider>
          <TooltipProvider>
            <UserProvider initialUser={initialUser}>{children}</UserProvider>
            {/* Google Identity Services SDK */}
            <Script
              src="https://accounts.google.com/gsi/client"
              strategy="afterInteractive"
            />
            <Toaster />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
